# Generated by Django 2.1.5 on 2020-04-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='ok',
            field=models.BooleanField(default=True),
        ),
    ]
