# Generated by Django 2.1.5 on 2020-04-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200402_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='ok',
            new_name='user_lists',
        ),
    ]
